<?php

/**
 * @file
 * Contains smmg_newsletter.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function smmg_newsletter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the smmg_newsletter module.
    case 'help.page.smmg_newsletter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Small Messages Plugin for Newsletter') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function smmg_newsletter_theme() {
  return [
    'smmg_newsletter' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_mail().
 */
function smmg_newsletter_mail($key, &$message, $params)
{

  switch ($key) {


    case 'EMAIL_PLAIN':

      $message['from'] = $params['from'];
      $message['subject'] = $params['title'];
      $message['body'][] = $params['message_plain'];
      break;


    case 'EMAIL_SMTP' :

      $message['from'] = $params['from'];
      $message['subject'] = $params['title'];
      $message['headers'] = [
        'MIME-Version' => '1.0',
        'Content-Type' => "multipart/alternative",
        'Content-Transfer-Encoding' => '8Bit',
        'X-Mailer' => 'Drupal',
      ];
      $message['body'][] = "\r\n--\r\n";
      $message['body'][] = 'Content-Type: text/plain; charset=utf-8;';
      $message['body'][] = $params['message_plain'];
      $message['body'][] = "\r\n--\r\n";
      $message['body'][] = "Content-Type: text/html; charset=utf-8;";
      $message['body'][] = $params['message_html'];
      $message['body'][] = "\r\n-- --\r\n";
      break;
  }

}
